// Generated by scripts/seed-prototype-assets.mjs
//
// Phase 4 placeholder. After `pac code add-data-source` generates src/generated/** for
// the three Dataverse tables, implement each repository here by wrapping the generated
// services in adapters that map connector records into the domain models in src/types.
// Keep the UI-facing AppDataProvider contract stable so screens are untouched by the swap.

import type { AppDataProvider } from '@/services/data-contracts';
import { getFieldMetadata } from '@/services/field-metadata-cache';

function notImplemented(member: string): never {
  throw new Error(
    `${member} is not implemented yet. The prototype runs on the mock provider — ` +
      `implement the real Dataverse provider in src/services/real-data-provider.ts (Phase 4).`,
  );
}

export function createRealDataProvider(): AppDataProvider {
  return {
    documents: {
      async list() {
        return notImplemented('documents.list()');
      },
      async getById() {
        return notImplemented('documents.getById()');
      },
      async create() {
        return notImplemented('documents.create()');
      },
      async update() {
        return notImplemented('documents.update()');
      },
    },
    documentTypes: {
      async list() {
        return notImplemented('documentTypes.list()');
      },
      async create() {
        return notImplemented('documentTypes.create()');
      },
      async update() {
        return notImplemented('documentTypes.update()');
      },
    },
    reviewSettings: {
      async get() {
        return notImplemented('reviewSettings.get()');
      },
      async update() {
        return notImplemented('reviewSettings.update()');
      },
    },
    skillUpdateRequests: {
      async list() {
        return notImplemented('skillUpdateRequests.list()');
      },
      async getById() {
        return notImplemented('skillUpdateRequests.getById()');
      },
      async create() {
        return notImplemented('skillUpdateRequests.create()');
      },
      async update() {
        return notImplemented('skillUpdateRequests.update()');
      },
    },
    sourceFiles: {
      async getSourceFileUrl() {
        return notImplemented('sourceFiles.getSourceFileUrl()');
      },
    },
    fieldMetadata: { getField: getFieldMetadata },
  } satisfies AppDataProvider;
}
